-- AlterTable
ALTER TABLE "User" ALTER COLUMN "notification" SET DEFAULT false,
ALTER COLUMN "allNotification" SET DEFAULT false,
ALTER COLUMN "creditBalance" SET DEFAULT 0,
ALTER COLUMN "creditPeriod" DROP NOT NULL,
ALTER COLUMN "pwExpiredOn" DROP NOT NULL,
ALTER COLUMN "createdOn" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updatedOn" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "subscription" SET DEFAULT false;
